# Generated by Django 4.2 on 2023-05-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciver',
            name='email',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='reciver',
            name='image',
            field=models.FileField(blank=True, upload_to='patient/'),
        ),
    ]
