# Generated by Django 4.2 on 2023-05-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_reciver_email_alter_reciver_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciver',
            name='image',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
